// ── feature: reputation · owner: Ozias ──
// A POSITIVE trust signal for scoring — the one thing Orbis lacked. Everything else in the scorer is
// subtractive (penalties only), so a legitimate-but-NICHE site (a local gym's survey, scholarship.com,
// a small school) could only ever lose points and never earn trust — and then its weak leg vetoed the
// whole forwarded-email verdict via worst-of. This module answers ONE question deterministically:
//
//   isReputableDomain(host) → is this the registered domain of a recognized, established site?
//
// WHY membership and not domain age / DKIM-pass: a trust floor must rest on something a fresh scam
// domain CANNOT fabricate. A brand-new phishing domain can pass DKIM/DMARC on its own domain and can
// have any WHOIS age story we can't cheaply verify — but it cannot retroactively appear in a
// pre-compiled popularity list, and it isn't on our hand-curated allowlist. So reputation is the
// false-negative-safe positive signal. (It NEVER overrides a hard danger signal — the callers gate the
// floor behind blacklist / urlscan-malicious / impersonation checks. See verdict.js / senderReport.js.)
//
// Three layers, combined at import (pure, offline, no API key):
//   1. CURATED allowlist (reputation-allowlist.js) — hand-kept, seeded with the exact sites users hit
//      + major ESP/survey/SaaS vendors. The precision layer + escape hatch for any niche site.
//   2. POPULARITY list (data/reputable-domains.txt) — Tranco top-50k, UGC-filtered, generated by
//      scripts/fetch-top-domains.mjs. Recall for the mainstream vendor/infra ecosystem.
//   3. NEVER_REPUTABLE denylist — shared-hosting / shortener / cloud domains that are POPULAR but host
//      arbitrary third-party pages (bit.ly, pages.dev, github.io, amazonaws.com…). These are stripped
//      from BOTH layers so "evil-phish.pages.dev" is never treated as reputable just because
//      pages.dev ranks high.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { registeredDomain } from "./typosquat.js";
import { CURATED_REPUTABLE } from "./data/reputation-allowlist.js";

// Domains that are popular BUT host user-generated / third-party content, or shorten arbitrary URLs.
// A high rank here means "lots of people use the platform", NOT "this specific page is trustworthy" —
// so membership must never grant a trust floor. Compared against the REGISTERED domain, so
// "evil.pages.dev" → "pages.dev" (denied) and "bit.ly/xyz" → "bit.ly" (denied). Exported so the
// generator (scripts/fetch-top-domains.mjs) filters the popularity list with the SAME set — the
// generation-time and runtime filters can never drift.
export const NEVER_REPUTABLE = new Set([
  // URL shorteners (the destination, not the shortener, is what matters)
  "bit.ly", "tinyurl.com", "t.co", "goo.gl", "ow.ly", "buff.ly", "rebrand.ly", "cutt.ly",
  "is.gd", "shorturl.at", "rb.gy", "lnkd.in", "t.ly",
  // Website builders / free hosting (anyone can publish anything on a subdomain)
  "wordpress.com", "blogspot.com", "weebly.com", "wixsite.com", "webflow.io", "squarespace.com",
  "tumblr.com", "medium.com", "substack.com", "godaddysites.com", "square.site", "myshopify.com",
  // Developer/app hosting (free subdomains → common phishing infra)
  "github.io", "gitlab.io", "pages.dev", "workers.dev", "netlify.app", "vercel.app", "web.app",
  "firebaseapp.com", "herokuapp.com", "glitch.me", "replit.app", "repl.co", "surge.sh",
  "onrender.com", "fly.dev", "000webhostapp.com", "r2.dev", "translate.goog",
  // Raw cloud object/compute hosts (buckets serve attacker-controlled files)
  "amazonaws.com", "azurewebsites.net", "windows.net", "cloudfront.net", "digitaloceanspaces.com",
  "storage.googleapis.com", "googleapis.com", "googleusercontent.com", "blob.core.windows.net",
  "backblazeb2.com", "b-cdn.net", "cdn.digitaloceanspaces.com",
  // Form / survey / e-sign / scheduling / event platforms. These are LEGITIMATE companies, but the
  // pages/links users receive live on user-created content ("myscam.typeform.com", a phishing
  // SurveyMonkey survey, a fake DocuSign "you have a document to sign") — abusing a trusted survey/
  // e-sign brand to slip past filters is a well-known technique. So the platform's reputation must
  // NOT transfer to an arbitrary form/link hosted on it. A survey on a business's OWN domain
  // (survey.fitnesssf.com) is still trusted via that domain; a survey on surveymonkey.com is not.
  "surveymonkey.com", "typeform.com", "jotform.com", "qualtrics.com", "formstack.com",
  "alchemer.com", "surveygizmo.com", "google.com", // google.com also fronts forms/docs/sites UGC;
                // real Google is recognized as a brand via knownBrandDomain, so denying it here only
                // blocks the UGC-floor path (a Google Forms phishing page won't be auto-trusted).
  "eventbrite.com", "calendly.com", "docusign.net", "docusign.com", "smartsheet.com",
  "notion.site", "paperform.co", "pastebin.com", "ipfs.io", "dweb.link", "campaign-archive.com",
]);

// Load the bundled popularity list once. It's DATA that may be absent in a fresh checkout (before the
// generator has been run) — so a missing/empty file degrades gracefully to "curated list only" rather
// than throwing and taking down scoring. Each line is one registered domain.
const loadPopularitySet = () => {
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    const raw = readFileSync(resolve(here, "data/reputable-domains.txt"), "utf8");
    const set = new Set();
    for (const line of raw.split("\n")) {
      const d = line.trim().toLowerCase();
      if (d && !d.startsWith("#") && !NEVER_REPUTABLE.has(d)) set.add(d);
    }
    return set;
  } catch {
    // No bundled list yet → curated allowlist still works. (Logged once, not per-call.)
    console.warn("⚠ reputation: bundled popularity list not found — using curated allowlist only. Run `node scripts/fetch-top-domains.mjs` to generate it.");
    return new Set();
  }
};

const POPULARITY = loadPopularitySet();

// The curated set, normalized + UGC-filtered the same way (so a mistaken UGC entry can't sneak trust).
const CURATED = new Set(
  CURATED_REPUTABLE
    .map((d) => registeredDomain(String(d).toLowerCase()) || String(d).toLowerCase())
    .filter((d) => d && !NEVER_REPUTABLE.has(d))
);

// Is this host's REGISTERED domain a recognized, established site? Folds "survey.fitnesssf.com" →
// "fitnesssf.com" before checking, so subdomains inherit the parent's reputation — EXCEPT for the
// denylist, which is applied to the registered domain so shared-hosting subdomains never qualify.
// Pure, offline, deterministic → same input always yields the same answer (unit-testable).
export const isReputableDomain = (host) => {
  const reg = registeredDomain(String(host || "").toLowerCase());
  if (!reg) return false;
  if (NEVER_REPUTABLE.has(reg)) return false; // popular shared-hosting/shortener → never a trust signal
  return CURATED.has(reg) || POPULARITY.has(reg);
};
